package com.example.vo;

import java.util.List;

public class TypeVO {
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.drinkIds
     *
     * @mbggenerated
     */
    private String[] drinkids;

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String[] getDrinkids() {
        return drinkids;
    }

    public void setDrinkids(String[] drinkids) {
        this.drinkids = drinkids;
    }
}
