package com.example.pojo;

public class Drink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drink.drinkId
     *
     * @mbggenerated
     */
    private String drinkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drink.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drink.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drink.picUrl
     *
     * @mbggenerated
     */
    private String picurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drink.drinkId
     *
     * @return the value of drink.drinkId
     *
     * @mbggenerated
     */
    public String getDrinkid() {
        return drinkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drink.drinkId
     *
     * @param drinkid the value for drink.drinkId
     *
     * @mbggenerated
     */
    public void setDrinkid(String drinkid) {
        this.drinkid = drinkid == null ? null : drinkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drink.name
     *
     * @return the value of drink.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drink.name
     *
     * @param name the value for drink.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drink.price
     *
     * @return the value of drink.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drink.price
     *
     * @param price the value for drink.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drink.picUrl
     *
     * @return the value of drink.picUrl
     *
     * @mbggenerated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drink.picUrl
     *
     * @param picurl the value for drink.picUrl
     *
     * @mbggenerated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }
}