package com.example.pojo;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.typeId
     *
     * @mbggenerated
     */
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.drinkIds
     *
     * @mbggenerated
     */
    private String drinkids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.typeId
     *
     * @return the value of type.typeId
     *
     * @mbggenerated
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.typeId
     *
     * @param typeid the value for type.typeId
     *
     * @mbggenerated
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.name
     *
     * @return the value of type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.name
     *
     * @param name the value for type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.drinkIds
     *
     * @return the value of type.drinkIds
     *
     * @mbggenerated
     */
    public String getDrinkids() {
        return drinkids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.drinkIds
     *
     * @param drinkids the value for type.drinkIds
     *
     * @mbggenerated
     */
    public void setDrinkids(String drinkids) {
        this.drinkids = drinkids == null ? null : drinkids.trim();
    }
}