package com.example.mapper;

import com.example.pojo.Drink;
import com.example.pojo.DrinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int countByExample(DrinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int deleteByExample(DrinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String drinkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int insert(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int insertSelective(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    List<Drink> selectByExample(DrinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    Drink selectByPrimaryKey(String drinkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Drink record, @Param("example") DrinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Drink record, @Param("example") DrinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Drink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drink
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Drink record);
}